import { v4 as uuidv4 } from 'uuid'; import { IEventPublisher } from '../../../../shared/application/ports/messaging'; import { EventEnvelope } from '../../../../shared/domain/events'; import * as E from '../../domain/events'; import * as S from '../../../../shared/domain/events/schemas/injection-molding.schema'
function env<T>(e:{eventType:string;eventVersion:string;payload:T},ctx:string,aggId:string,aggType:string,c:{tenantId:string;userId:string;agentId?:string|null;correlationId?:string;causationId?:string|null}):EventEnvelope<T>{return {eventId:uuidv4(),eventType:e.eventType,eventVersion:e.eventVersion,timestamp:new Date().toISOString(),correlationId:c.correlationId??uuidv4(),causationId:c.causationId??null,tenantId:c.tenantId,source:{context:ctx,aggregateId:aggId,aggregateType:aggType},payload:e.payload,metadata:{userId:c.userId,agentId:c.agentId??null,channel:c.agentId?'agent':'api'}}}
type C={tenantId:string;userId:string;agentId?:string|null;correlationId?:string;causationId?:string|null}
export class PublishRunStarted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.RunStartedPayload}){ const v=S.RunStartedPayload.parse(c.payload); const e=env(new E.RunStartedEvent(v),'injection-molding',v.runId,'ProductionRun',c); await this.p.publish(e); return e } }
export class PublishCycleCompleted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.CycleCompletedPayload}){ const v=S.CycleCompletedPayload.parse(c.payload); const e=env(new E.CycleCompletedEvent(v),'injection-molding',v.cycleId,'Cycle',c); await this.p.publish(e); return e } }
export class PublishDefectDetected { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.DefectDetectedPayload}){ const v=S.DefectDetectedPayload.parse(c.payload); const e=env(new E.DefectDetectedEvent(v),'injection-molding',v.defectId,'Defect',c); await this.p.publish(e); return e } }
export class PublishBatchCompleted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.BatchCompletedPayload}){ const v=S.BatchCompletedPayload.parse(c.payload); const e=env(new E.BatchCompletedEvent(v),'injection-molding',v.batchId,'Batch',c); await this.p.publish(e); return e } }
export class PublishRunCompleted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.RunCompletedPayload}){ const v=S.RunCompletedPayload.parse(c.payload); const e=env(new E.RunCompletedEvent(v),'injection-molding',v.runId,'ProductionRun',c); await this.p.publish(e); return e } }
export class PublishMachineStopped { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.MachineStoppedPayload}){ const v=S.MachineStoppedPayload.parse(c.payload); const e=env(new E.MachineStoppedEvent(v),'injection-molding',v.stopId,'MachineStop',c); await this.p.publish(e); return e } }
export class PublishParameterChanged { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.ParameterChangedPayload}){ const v=S.ParameterChangedPayload.parse(c.payload); const e=env(new E.ParameterChangedEvent(v),'injection-molding',v.changeId,'ParameterChange',c); await this.p.publish(e); return e } }
export class PublishQualityCheckPassed { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.QualityCheckPassedPayload}){ const v=S.QualityCheckPassedPayload.parse(c.payload); const e=env(new E.QualityCheckPassedEvent(v),'injection-molding',v.checkId,'QualityCheck',c); await this.p.publish(e); return e } }
export class PublishScrapRecorded { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.ScrapRecordedPayload}){ const v=S.ScrapRecordedPayload.parse(c.payload); const e=env(new E.ScrapRecordedEvent(v),'injection-molding',v.scrapId,'Scrap',c); await this.p.publish(e); return e } }
export class PublishMoldChangeCompleted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.MoldChangeCompletedPayload}){ const v=S.MoldChangeCompletedPayload.parse(c.payload); const e=env(new E.MoldChangeCompletedEvent(v),'injection-molding',v.changeId,'MoldChange',c); await this.p.publish(e); return e } }
