"use client";
import { useEffect, useState } from "react";
interface C { id: number; vendedor_id: number; nome: string; total_vendas: number; comissao_pct: number; total_comissoes: number; mes: string; status: string; }
export default function Page() {
  const [items,setItems]=useState<C[]>([]);const[loading,setLoading]=useState(true);const[show,setShow]=useState(false);const[f,setF]=useState<Record<string,string>>({});
  const load=()=>{fetch("/api/rh/comissoes").then(r=>r.json()).then(d=>setItems((d.data||[]) as C[])).catch(()=>{}).finally(()=>setLoading(false));};
  useEffect(()=>{load();},[]);
  const save=async()=>{const tv=parseFloat(f.total_vendas||"0");const pc=parseFloat(f.comissao_pct||"0");await fetch("/api/rh/comissoes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,total_vendas:tv,comissao_pct:pc,total_comissoes:tv*pc/100})});setShow(false);setF({});load();};
  const pay=async(id:number)=>{await fetch("/api/rh/comissoes/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"pago"})});load();};
  const total=items.filter(i=>i.status!=="pago").reduce((s,i)=>s+(i.total_comissoes||0),0);
  return (<div className="p-6 space-y-4">
    <div className="flex items-center justify-between"><div><h1 className="text-lg font-bold text-neutral-100">Comissoes</h1><p className="text-xs text-neutral-500 mt-1">Pendente: R$ {total.toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div><button onClick={()=>{setF({});setShow(!show)}} className="px-3 py-1.5 bg-orange-600 text-white text-xs rounded-lg">+ Nova</button></div>
    {show&&(<div className="bg-neutral-800 border border-neutral-700 rounded-lg p-4 space-y-3"><h3 className="text-sm font-semibold text-neutral-200">Nova Comissao</h3><div className="grid grid-cols-2 gap-3">{[["vendedor_id","ID Vend"],["nome","Nome"],["mes","Mes"],["total_vendas","Total Vendas"],["comissao_pct","% Comissao"]].map(([k,l])=>(<div key={k}><label className="text-xs text-neutral-500">{l}</label><input type={k.includes("total")||k.includes("pct")?"number":"text"} value={f[k]||""} onChange={e=>setF({...f,[k]:e.target.value})} className="w-full bg-neutral-900 border border-neutral-700 rounded px-2 py-1.5 text-xs text-neutral-200 mt-1"/></div>))}</div><div className="flex gap-2"><button onClick={save} className="px-3 py-1 bg-emerald-600 text-white text-xs rounded">Salvar</button><button onClick={()=>setShow(false)} className="px-3 py-1 text-xs text-neutral-400">Cancelar</button></div></div>)}
    {loading?<p className="text-neutral-500 text-sm">Carregando...</p>:items.length===0?<p className="text-neutral-500">Nenhuma</p>:(
      <div className="bg-neutral-800 border border-neutral-700 rounded-lg overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-neutral-700 text-neutral-400 bg-neutral-850">{["Vendedor","Mes","Total Vendas","%","Comissao","Status"].map(c=><th key={c} className="text-left p-2">{c}</th>)}<th className="text-right p-2">Acao</th></tr></thead><tbody>{items.map((c,i)=>(<tr key={c.id} className={"border-b border-neutral-700/50 "+(i%2===0?"bg-neutral-800":"bg-neutral-800/50")}><td className="p-2 text-neutral-200">{c.nome}</td><td className="p-2 text-neutral-400">{c.mes}</td><td className="p-2">R$ {(c.total_vendas||0).toFixed(2)}</td><td className="p-2">{c.comissao_pct}%</td><td className="p-2 text-emerald-400 font-medium">R$ {(c.total_comissoes||0).toFixed(2)}</td><td className="p-2"><span className={"px-1.5 py-0.5 rounded text-[9px] "+(c.status==="pago"?"text-emerald-400 bg-emerald-900/30":"text-amber-400 bg-amber-900/30")}>{c.status||"pendente"}</span></td><td className="p-2 text-right">{c.status!=="pago"&&<button onClick={()=>pay(c.id)} className="text-emerald-400 hover:text-emerald-300 text-xs">Pagar</button>}</td></tr>))}</tbody></table></div>)}</div>);
}
