import { v4 as uuidv4 } from 'uuid'; import { IEventPublisher } from '../../../../shared/application/ports/messaging'; import { EventEnvelope } from '../../../../shared/domain/events'; import * as E from '../../domain/events'; import * as S from '../../../../shared/domain/events/schemas/plastisol-processing.schema'
function env<T>(e:{eventType:string;eventVersion:string;payload:T},ctx:string,aggId:string,aggType:string,c:{tenantId:string;userId:string;agentId?:string|null;correlationId?:string;causationId?:string|null}):EventEnvelope<T>{return {eventId:uuidv4(),eventType:e.eventType,eventVersion:e.eventVersion,timestamp:new Date().toISOString(),correlationId:c.correlationId??uuidv4(),causationId:c.causationId??null,tenantId:c.tenantId,source:{context:ctx,aggregateId:aggId,aggregateType:aggType},payload:e.payload,metadata:{userId:c.userId,agentId:c.agentId??null,channel:c.agentId?'agent':'api'}}}
type C={tenantId:string;userId:string;agentId?:string|null;correlationId?:string;causationId?:string|null}
export class PublishFormulationMixed { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.FormulationMixedPayload}){ const v=S.FormulationMixedPayload.parse(c.payload); const e=env(new E.FormulationMixedEvent(v),'plastisol-processing',v.formulationId,'Formulation',c); await this.p.publish(e); return e } }
export class PublishDippingStarted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.DippingStartedPayload}){ const v=S.DippingStartedPayload.parse(c.payload); const e=env(new E.DippingStartedEvent(v),'plastisol-processing',v.dippingId,'Dipping',c); await this.p.publish(e); return e } }
export class PublishDippingCompleted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.DippingCompletedPayload}){ const v=S.DippingCompletedPayload.parse(c.payload); const e=env(new E.DippingCompletedEvent(v),'plastisol-processing',v.dippingId,'Dipping',c); await this.p.publish(e); return e } }
export class PublishCuringStarted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.CuringStartedPayload}){ const v=S.CuringStartedPayload.parse(c.payload); const e=env(new E.CuringStartedEvent(v),'plastisol-processing',v.curingId,'Curing',c); await this.p.publish(e); return e } }
export class PublishCuringCompleted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.CuringCompletedPayload}){ const v=S.CuringCompletedPayload.parse(c.payload); const e=env(new E.CuringCompletedEvent(v),'plastisol-processing',v.curingId,'Curing',c); await this.p.publish(e); return e } }
export class PublishBatchCompleted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.BatchCompletedPayload}){ const v=S.BatchCompletedPayload.parse(c.payload); const e=env(new E.BatchCompletedEvent(v),'plastisol-processing',v.batchId,'Batch',c); await this.p.publish(e); return e } }
export class PublishQCResultRecorded { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.QCResultRecordedPayload}){ const v=S.QCResultRecordedPayload.parse(c.payload); const e=env(new E.QCResultRecordedEvent(v),'plastisol-processing',v.qcId,'QCResult',c); await this.p.publish(e); return e } }
export class PublishViscosityAdjusted { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.ViscosityAdjustedPayload}){ const v=S.ViscosityAdjustedPayload.parse(c.payload); const e=env(new E.ViscosityAdjustedEvent(v),'plastisol-processing',v.formulationId,'Formulation',c); await this.p.publish(e); return e } }
export class PublishCoatingSpecUpdated { constructor(private p:IEventPublisher){} async execute(c:C&{payload:E.CoatingSpecUpdatedPayload}){ const v=S.CoatingSpecUpdatedPayload.parse(c.payload); const e=env(new E.CoatingSpecUpdatedEvent(v),'plastisol-processing',v.specId,'CoatingSpec',c); await this.p.publish(e); return e } }
