{
  "version": "7.8.0",
  "steps": [
    {
      "tag": "CreateSource",
      "source": "Schema",
      "sourceSchema": "generator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n}\n"
    }
  ]
}
