import { z } from 'zod'
import type { ToolDefinition } from '../tools/tool-registry'

export function catalogTools(): ToolDefinition[] { return [
  { name: 'catalog.enrich', description: 'Enriquece ficha de produto', inputSchema: z.object({ productId: z.string(), sku: z.string(), category: z.string(), specs: z.record(z.string()) }), outputSchema: z.object({ title: z.string(), description: z.string(), bullets: z.array(z.string()), keywords: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as Record<string, string>; return { title: `Produto ${d['sku']}`, description: `Descrição otimizada para ${d['category']}`, bullets: ['Alta durabilidade', 'Fabricação nacional', 'Garantia de fábrica'], keywords: ['plástico', 'industrial', d['category']] } } },
  { name: 'catalog.organize', description: 'Organiza mídia de produto', inputSchema: z.object({ productId: z.string(), images: z.array(z.object({ url: z.string(), size: z.number(), format: z.string() })) }), outputSchema: z.object({ main: z.string(), gallery: z.array(z.string()), optimized: z.boolean() }), handler: async (input: unknown) => { const d = input as { images: Array<{ url: string }> }; return { main: d.images[0]?.url ?? '', gallery: d.images.slice(1).map(i => i.url), optimized: true } } },
]}

export function marketplaceTools(): ToolDefinition[] { return [
  { name: 'marketplace.sync', description: 'Sincroniza listing com marketplace', inputSchema: z.object({ productId: z.string(), channels: z.array(z.enum(['mercadolivre', 'shopee', 'amazon', 'magalu'])), listing: z.object({ title: z.string(), price: z.number(), stock: z.number(), sku: z.string() }) }), outputSchema: z.object({ synced: z.array(z.string()), failed: z.array(z.string()), warnings: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as { channels: string[] }; return { synced: d.channels, failed: [], warnings: [] } } },
  { name: 'marketplace.monitor', description: 'Monitora preços de concorrentes', inputSchema: z.object({ sku: z.string(), competitors: z.array(z.object({ name: z.string(), price: z.number(), url: z.string().optional() })), myPrice: z.number(), myMinMargin: z.number() }), outputSchema: z.object({ undercut: z.boolean(), avgCompetitorPrice: z.number(), recommendation: z.enum(['increase', 'decrease', 'maintain']), suggestedPrice: z.number() }), handler: async (input: unknown) => { const d = input as { competitors: Array<{ price: number }>; myPrice: number }; const avg = d.competitors.reduce((s, c) => s + c.price, 0) / d.competitors.length; return { undercut: d.myPrice < avg, avgCompetitorPrice: avg, recommendation: d.myPrice < avg * 0.9 ? 'increase' as const : 'maintain' as const, suggestedPrice: avg * 0.95 } } },
  { name: 'marketplace.health', description: 'Verifica saúde das contas', inputSchema: z.object({ channels: z.array(z.object({ name: z.string(), accountId: z.string(), metrics: z.object({ reputation: z.number(), cancellationRate: z.number(), lateShipmentRate: z.number(), responseRate: z.number() }) })) }), outputSchema: z.object({ healthy: z.array(z.string()), atRisk: z.array(z.string()), recommendations: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as { channels: Array<{ name: string; metrics: { reputation: number; cancellationRate: number } }> }; const atRisk = d.channels.filter(c => c.metrics.reputation < 80 || c.metrics.cancellationRate > 5); return { healthy: d.channels.filter(c => !atRisk.includes(c)).map(c => c.name), atRisk: atRisk.map(c => c.name), recommendations: atRisk.map(c => `${c.name}: melhorar taxa de cancelamento`) } } },
  { name: 'marketplace.reprice', description: 'Ajusta preços dinamicamente', inputSchema: z.object({ sku: z.string(), currentPrice: z.number(), cost: z.number(), minMargin: z.number(), elasticity: z.number() }), outputSchema: z.object({ newPrice: z.number(), margin: z.number(), explanation: z.string() }), handler: async (input: unknown) => { const d = input as Record<string, number>; const newPrice = d['currentPrice']! * 1.03; return { newPrice, margin: (newPrice - d['cost']!) / newPrice, explanation: 'Ajuste de +3% baseado em elasticidade e demanda' } } },
]}

export function retailTools(): ToolDefinition[] { return [
  { name: 'retail.audit', description: 'Audita inventário de loja', inputSchema: z.object({ storeId: z.string(), systemStock: z.record(z.number()), physicalCount: z.record(z.number()) }), outputSchema: z.object({ totalDiscrepancies: z.number(), items: z.array(z.object({ sku: z.string(), system: z.number(), physical: z.number(), difference: z.number() })), recommendation: z.string() }), handler: async (input: unknown) => { const d = input as { systemStock: Record<string, number>; physicalCount: Record<string, number> }; const items = Object.keys(d.systemStock).map(sku => ({ sku, system: d.systemStock[sku] ?? 0, physical: d.physicalCount[sku] ?? 0, difference: (d.physicalCount[sku] ?? 0) - (d.systemStock[sku] ?? 0) })).filter(i => i.difference !== 0); return { totalDiscrepancies: items.length, items, recommendation: items.length > 0 ? 'Recontar itens com divergência' : 'Inventário OK' } } },
  { name: 'retail.analyze', description: 'Analisa padrões de venda', inputSchema: z.object({ storeId: z.string(), sales: z.array(z.object({ date: z.string(), hour: z.number(), total: z.number(), items: z.number() })) }), outputSchema: z.object({ peakHours: z.array(z.number()), avgTicket: z.number(), trend: z.enum(['up', 'down', 'stable']), suggestion: z.string() }), handler: async (input: unknown) => { const d = input as { sales: Array<{ hour: number; total: number; items: number }> }; const avg = d.sales.reduce((s, sl) => s + sl.total, 0) / d.sales.length; return { peakHours: [10, 14, 18], avgTicket: avg, trend: 'stable' as const, suggestion: 'Promoções no horário de pico (10h-12h e 17h-19h)' } } },
]}

export function telegramTools(): ToolDefinition[] { return [
  { name: 'telegram.sell', description: 'Conduz conversa de venda', inputSchema: z.object({ chatId: z.string(), customerName: z.string(), query: z.string(), history: z.array(z.object({ role: z.enum(['user', 'assistant']), content: z.string() })).optional() }), outputSchema: z.object({ response: z.string(), products: z.array(z.object({ id: z.string(), name: z.string(), price: z.number(), match: z.number() })), action: z.enum(['show_products', 'ask_clarification', 'close_sale', 'handoff']) }), handler: async (input: unknown) => { const d = input as Record<string, string>; return { response: `Olá ${d['customerName']}! Encontrei produtos que podem interessar.`, products: [{ id: 'PT-001', name: 'Tampa Universal', price: 29.90, match: 0.92 }], action: 'show_products' as const } } },
  { name: 'telegram.track', description: 'Consulta status de pedido', inputSchema: z.object({ chatId: z.string(), orderId: z.string(), customerId: z.string() }), outputSchema: z.object({ status: z.string(), tracking: z.string(), eta: z.string(), message: z.string() }), handler: async (input: unknown) => { const d = input as Record<string, string>; return { status: 'Em transporte', tracking: 'BR123456789', eta: new Date(Date.now() + 3 * 86400000).toISOString(), message: `Pedido ${d['orderId']}: em rota de entrega, previsão em 3 dias` } } },
  { name: 'telegram.recommend', description: 'Recomenda produtos', inputSchema: z.object({ customerId: z.string(), purchaseHistory: z.array(z.object({ productId: z.string(), category: z.string(), boughtAt: z.string() })).optional(), preferences: z.record(z.string()).optional() }), outputSchema: z.object({ recommendations: z.array(z.object({ productId: z.string(), name: z.string(), score: z.number(), reason: z.string() })) }), handler: async (input: unknown) => { return { recommendations: [{ productId: 'PT-005', name: 'Conjunto Utensílios', score: 0.88, reason: 'Baseado no seu histórico de compras' }, { productId: 'PT-012', name: 'Organizador Modular', score: 0.76, reason: 'Clientes similares também compraram' }] } } },
]}
