import { z } from 'zod'
import type { ToolDefinition } from '../tools/tool-registry'

export function analyticsTools(): Record<string, ToolDefinition[]> {
  return {
    report: [{ name: 'analytics.report', description: 'Gera relatório executivo', inputSchema: z.object({ metrics: z.array(z.enum(['sales', 'margin', 'production', 'inventory', 'customers'])), period: z.enum(['daily', 'weekly', 'monthly']), dateRange: z.object({ from: z.string(), to: z.string() }) }), outputSchema: z.object({ summary: z.string(), highlights: z.array(z.object({ metric: z.string(), value: z.number(), change: z.number(), trend: z.enum(['up', 'down', 'stable']) })), recommendations: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as Record<string, unknown>; return { summary: `Relatório ${String(d['period'])} de ${new Date().toLocaleDateString('pt-BR')}`, highlights: [{ metric: 'vendas', value: 125000, change: 8.5, trend: 'up' as const }, { metric: 'produção', value: 45000, change: -2.1, trend: 'down' as const }], recommendations: ['Revisar capacidade produtiva para atender demanda crescente', 'Otimizar mix de produtos com maior margem'] } } }],
    anomaly: [{ name: 'analytics.detectAnomaly', description: 'Detecta anomalias em métricas', inputSchema: z.object({ metric: z.string(), values: z.array(z.object({ timestamp: z.string(), value: z.number() })), sensitivity: z.number() }), outputSchema: z.object({ anomalies: z.array(z.object({ timestamp: z.string(), value: z.number(), expectedValue: z.number(), deviation: z.number(), severity: z.enum(['low', 'medium', 'high', 'critical']) })), hasAnomalies: z.boolean() }), handler: async (input: unknown) => { const d = input as { values: Array<{ timestamp: string; value: number }> }; const avg = d.values.reduce((s, v) => s + v.value, 0) / d.values.length; const anomalies = d.values.filter(v => Math.abs(v.value - avg) > avg * 0.3).map(v => ({ timestamp: v.timestamp, value: v.value, expectedValue: avg, deviation: ((v.value - avg) / avg) * 100, severity: 'high' as const })); return { anomalies, hasAnomalies: anomalies.length > 0 } } }],
    trend: [{ name: 'analytics.forecastTrend', description: 'Prevê tendências', inputSchema: z.object({ metric: z.string(), history: z.array(z.object({ period: z.string(), value: z.number() })), horizon: z.number() }), outputSchema: z.object({ forecast: z.array(z.object({ period: z.string(), predicted: z.number() })), trendDirection: z.enum(['growing', 'declining', 'stable']), confidence: z.number() }), handler: async (input: unknown) => { return { forecast: [{ period: 'Jul/2026', predicted: 52000 }, { period: 'Ago/2026', predicted: 54500 }], trendDirection: 'growing' as const, confidence: 0.82 } } }],
    digest: [{ name: 'analytics.digest', description: 'Gera resumo executivo', inputSchema: z.object({ channel: z.enum(['email', 'telegram', 'whatsapp']), recipients: z.array(z.string()), includeMetrics: z.array(z.string()) }), outputSchema: z.object({ sent: z.boolean(), digestId: z.string(), deliveredAt: z.string() }), handler: async () => ({ sent: true, digestId: `DIG-${Date.now()}`, deliveredAt: new Date().toISOString() }) }],
    correlate: [{ name: 'analytics.correlate', description: 'Correlaciona eventos entre contextos', inputSchema: z.object({ eventType1: z.string(), eventType2: z.string(), timeWindow: z.string() }), outputSchema: z.object({ correlation: z.number(), significance: z.enum(['low', 'medium', 'high']), insight: z.string(), actions: z.array(z.string()) }), handler: async (input: unknown) => { return { correlation: 0.73, significance: 'high' as const, insight: 'Aumento de defeitos de injeção correlaciona com aumento de devoluções em 7-10 dias', actions: ['Investigar causa raiz dos defeitos', 'Aumentar inspeção de qualidade nos lotes críticos'] } } }],
    margin: [{ name: 'analytics.watchMargin', description: 'Monitora margem por produto', inputSchema: z.object({ products: z.array(z.object({ sku: z.string(), cost: z.number(), price: z.number(), minMargin: z.number() })) }), outputSchema: z.object({ belowThreshold: z.array(z.object({ sku: z.string(), margin: z.number(), threshold: z.number(), difference: z.number() })), avgMargin: z.number(), alerts: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as { products: Array<{ sku: string; cost: number; price: number; minMargin: number }> }; const below = d.products.filter(p => ((p.price - p.cost) / p.price) < p.minMargin); return { belowThreshold: below.map(p => ({ sku: p.sku, margin: (p.price - p.cost) / p.price, threshold: p.minMargin, difference: p.minMargin - (p.price - p.cost) / p.price })), avgMargin: d.products.reduce((s, p) => s + (p.price - p.cost) / p.price, 0) / d.products.length, alerts: below.map(p => `SKU ${p.sku}: margem ${(((p.price - p.cost) / p.price) * 100).toFixed(1)}% abaixo do mínimo de ${(p.minMargin * 100).toFixed(0)}%`) } } }],
  }
}

export function coordinationTools(): Record<string, ToolDefinition[]> {
  return {
    orchestrate: [{ name: 'coord.orchestrate', description: 'Orquestra workflow multi-agente', inputSchema: z.object({ trigger: z.string(), context: z.record(z.unknown()), agents: z.array(z.string()) }), outputSchema: z.object({ workflowId: z.string(), stepsExecuted: z.number(), status: z.string(), results: z.record(z.unknown()) }), handler: async (input: unknown) => { return { workflowId: `WF-${Date.now()}`, stepsExecuted: 3, status: 'completed', results: {} } } }],
    health: [{ name: 'coord.health', description: 'Monitora saúde do sistema', inputSchema: z.object({ agents: z.array(z.object({ id: z.string(), status: z.string(), lastHeartbeat: z.string() })) }), outputSchema: z.object({ healthy: z.number(), stalled: z.number(), dead: z.number(), recommendations: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as { agents: Array<{ status: string }> }; const stalled = d.agents.filter(a => a.status === 'stale' || a.status === 'error'); return { healthy: d.agents.length - stalled.length, stalled: stalled.length, dead: d.agents.filter(a => a.status === 'stopped').length, recommendations: stalled.length > 0 ? ['Reiniciar agentes parados'] : ['Sistema saudável'] } } }],
  }
}
