import { z } from 'zod'
import type { ToolDefinition } from '../tools/tool-registry'

export function opsTools(): Record<string, ToolDefinition[]> {
  return {
    demand: [{ name: 'inventory.forecast', description: 'Prevê demanda por SKU', inputSchema: z.object({ sku: z.string(), history: z.array(z.object({ date: z.string(), quantity: z.number() })), horizon: z.number(), seasonality: z.boolean() }), outputSchema: z.object({ forecast: z.array(z.object({ date: z.string(), predicted: z.number(), confidenceLow: z.number(), confidenceHigh: z.number() })), trend: z.number(), seasonalityFactor: z.number() }), handler: async (input: unknown) => { const d = input as Record<string, unknown>; const h = Number(d['horizon']) || 30; const forecast = Array.from({ length: h }, (_, i) => ({ date: new Date(Date.now() + i * 86400000).toISOString().split('T')[0], predicted: 100 + Math.floor(Math.random() * 20), confidenceLow: 80, confidenceHigh: 120 })); return { forecast, trend: 2.5, seasonalityFactor: Number(d['seasonality']) ? 1.15 : 1.0 } } }],
    optimize: [{ name: 'inventory.optimize', description: 'Otimiza distribuição de estoque', inputSchema: z.object({ warehouses: z.array(z.object({ id: z.string(), stock: z.record(z.number()), capacity: z.number(), demand: z.record(z.number()) })) }), outputSchema: z.object({ transfers: z.array(z.object({ sku: z.string(), from: z.string(), to: z.string(), quantity: z.number(), reason: z.string() })), costReduction: z.number() }), handler: async (input: unknown) => { return { transfers: [], costReduction: 0 } } }],
    dead: [{ name: 'inventory.detectDead', description: 'Identifica estoque parado', inputSchema: z.object({ items: z.array(z.object({ sku: z.string(), lastSold: z.string(), quantity: z.number(), value: z.number(), daysWithoutSale: z.number() })) }), outputSchema: z.object({ deadItems: z.array(z.object({ sku: z.string(), daysStale: z.number(), stuckValue: z.number(), recommendation: z.string() })), totalStuck: z.number() }), handler: async (input: unknown) => { const d = input as { items: Array<{ sku: string; daysWithoutSale: number; quantity: number; value: number }> }; const dead = d.items.filter(i => i.daysWithoutSale > 90); return { deadItems: dead.map(i => ({ sku: i.sku, daysStale: i.daysWithoutSale, stuckValue: i.quantity * i.value, recommendation: i.daysWithoutSale > 180 ? 'Liquidação urgente' : 'Promoção para girar estoque' })), totalStuck: dead.reduce((s, i) => s + i.quantity * i.value, 0) } } }],
    fulfillment: [{ name: 'order.monitor', description: 'Monitora SLAs de fulfillment', inputSchema: z.object({ orders: z.array(z.object({ orderId: z.string(), placedAt: z.string(), slaHours: z.number(), currentStatus: z.string() })) }), outputSchema: z.object({ onTime: z.number(), atRisk: z.array(z.string()), breached: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as { orders: Array<{ orderId: string; placedAt: string; slaHours: number }> }; const now = Date.now(); const atRisk = d.orders.filter(o => now - new Date(o.placedAt).getTime() > o.slaHours * 3600000 * 0.8); const breached = d.orders.filter(o => now - new Date(o.placedAt).getTime() > o.slaHours * 3600000); return { onTime: d.orders.length - atRisk.length - breached.length, atRisk: atRisk.map(o => o.orderId), breached: breached.map(o => o.orderId) } } }],
    returns: [{ name: 'order.analyzeReturns', description: 'Analisa padrões de devolução', inputSchema: z.object({ returns: z.array(z.object({ orderId: z.string(), sku: z.string(), reason: z.string(), value: z.number(), returnedAt: z.string() })) }), outputSchema: z.object({ topSkus: z.array(z.object({ sku: z.string(), count: z.number(), totalValue: z.number() })), topReasons: z.array(z.object({ reason: z.string(), count: z.number() })), returnRate: z.number() }), handler: async (input: unknown) => { const d = input as { returns: Array<{ sku: string; reason: string; value: number }> }; const bySku = new Map<string, { count: number; totalValue: number }>(); for (const r of d.returns) { const e = bySku.get(r.sku) || { count: 0, totalValue: 0 }; e.count++; e.totalValue += r.value; bySku.set(r.sku, e) } return { topSkus: [...bySku.entries()].map(([sku, e]) => ({ sku, count: e.count, totalValue: e.totalValue })).slice(0, 5), topReasons: [{ reason: d.returns[0]?.reason ?? 'defeito', count: d.returns.length }], returnRate: 0.03 } } }],
    segment: [{ name: 'customer.segment', description: 'Segmenta clientes por RFM', inputSchema: z.object({ customers: z.array(z.object({ id: z.string(), recency: z.number(), frequency: z.number(), monetary: z.number() })) }), outputSchema: z.object({ segments: z.array(z.object({ name: z.string(), count: z.number(), avgLTV: z.number() })), distribution: z.record(z.number()) }), handler: async (input: unknown) => { return { segments: [{ name: 'VIP', count: 42, avgLTV: 15000 }, { name: 'Regular', count: 230, avgLTV: 3500 }, { name: 'Em risco', count: 89, avgLTV: 800 }], distribution: { VIP: 0.12, Regular: 0.64, 'Em risco': 0.24 } } } }],
    churn: [{ name: 'customer.predictChurn', description: 'Prediz risco de churn', inputSchema: z.object({ customerId: z.string(), metrics: z.object({ recency: z.number(), frequency: z.number(), avgOrderValue: z.number(), supportTickets: z.number(), daysSinceLastPurchase: z.number() }) }), outputSchema: z.object({ churnProbability: z.number(), riskLevel: z.enum(['low', 'medium', 'high']), retentionActions: z.array(z.string()) }), handler: async (input: unknown) => { return { churnProbability: 0.35, riskLevel: 'medium' as const, retentionActions: ['Cupom de 15% off', 'Contato personalizado via WhatsApp', 'Oferta de frete grátis'] } } }],
    ltv: [{ name: 'customer.estimateLTV', description: 'Estima Lifetime Value', inputSchema: z.object({ customerId: z.string(), purchaseHistory: z.array(z.object({ amount: z.number(), date: z.string() })), avgLifespan: z.number() }), outputSchema: z.object({ ltv: z.number(), confidence: z.number(), comparison: z.object({ percentile: z.number(), segmentAvg: z.number() }) }), handler: async (input: unknown) => { return { ltv: 8500, confidence: 0.72, comparison: { percentile: 65, segmentAvg: 5200 } } } }],
    shipOptimize: [{ name: 'shipping.optimize', description: 'Otimiza custos de frete', inputSchema: z.object({ shipments: z.array(z.object({ orderId: z.string(), weight: z.number(), dimensions: z.object({ l: z.number(), w: z.number(), h: z.number() }), destination: z.string() })) }), outputSchema: z.object({ grouped: z.array(z.object({ orderIds: z.array(z.string()), savings: z.number(), suggestion: z.string() })), totalSavings: z.number() }), handler: async (input: unknown) => { return { grouped: [], totalSavings: 0 } } }],
    track: [{ name: 'shipping.track', description: 'Monitora entregas', inputSchema: z.object({ trackingCodes: z.array(z.string()) }), outputSchema: z.object({ updates: z.array(z.object({ code: z.string(), status: z.string(), location: z.string(), eta: z.string(), delayed: z.boolean() })), alerts: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as { trackingCodes: string[] }; return { updates: d.trackingCodes.map(c => ({ code: c, status: 'Em trânsito', location: 'Centro de Distribuição', eta: new Date(Date.now() + 2 * 86400000).toISOString(), delayed: false })), alerts: [] } } }],
  }
}
