import { AgentRuntime } from '../core/agent-runtime'
import { AgentContext } from '../core/agent-context'
import { DefaultMemoryManager } from '../memory/memory-manager'
import { DefaultToolRegistry, type ToolDefinition } from '../tools/tool-registry'
import { ToolExecutor } from '../tools/tool-executor'
import { z } from 'zod'
import type { AgentDefinition } from '../core/agent-types'

const makeAgent = (id: string, name: string, role: 'observer' | 'analyst' | 'decision-maker' | 'executor', context: string, systemPrompt: string, tools: ToolDefinition[]): AgentRuntime => {
  const memory = new DefaultMemoryManager()
  const registry = new DefaultToolRegistry()
  for (const t of tools) registry.register(t)
  const def: AgentDefinition = { id, name, role, context, systemPrompt, capabilities: tools.map(t => ({ name: t.name, description: t.description, inputSchema: {}, outputSchema: {} })), config: { modelProvider: 'openai', modelName: 'gpt-4o-mini', temperature: 0.2, maxTokens: 1024, retryPolicy: { maxRetries: 2, backoffMs: 500 }, timeout: 15000 } }
  const agent = new (class extends AgentRuntime { private exec: ToolExecutor; constructor() { super(id, def, new AgentContext(id, memory, registry)); this.exec = new ToolExecutor(registry) } override async handleTask(task: Record<string, unknown>): Promise<Record<string, unknown>> { await super.handleTask(task); const t = task['type'] as string; const tool = tools.find(tt => t.includes(tt.name.split('.')[0] ?? '')); if (tool) { const r = await this.exec.execute(tool.name, task); return { ...task, result: r } } return super.handleTask(task) } })()
  return agent
}

export function createMoldDesignReviewer() { return makeAgent('ag-004', 'mold-design-reviewer', 'analyst', 'mold-making', 'Analisa design do molde contra regras de manufaturabilidade, ângulos de saída, espessura de parede.', [{ name: 'mold.review', description: 'Review mold design', inputSchema: z.object({ moldId: z.string(), cavities: z.number(), material: z.string(), draftAngle: z.number(), wallThickness: z.number() }), outputSchema: z.object({ approved: z.boolean(), issues: z.array(z.string()), recommendations: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as Record<string, unknown>; const issues: string[] = []; if (Number(d['draftAngle']) < 1) issues.push('Ângulo de saída insuficiente (<1°)'); if (Number(d['wallThickness']) < 1.5) issues.push('Espessura de parede abaixo do mínimo (1.5mm)'); return { approved: issues.length === 0, issues, recommendations: issues.length > 0 ? ['Aumentar ângulo para ≥1.5°', 'Espessura mínima de 1.5mm recomendada'] : [] } } }]) }
export function createMoldMaintenancePredictor() { return makeAgent('ag-005', 'mold-maintenance-predictor', 'decision-maker', 'mold-making', 'Prediz necessidade de manutenção baseado em contagem de ciclos, material injetado, histórico de falhas.', [{ name: 'mold.predictMaintenance', description: 'Predict maintenance need', inputSchema: z.object({ moldId: z.string(), cycleCount: z.number(), materialType: z.string(), lastMaintenance: z.string(), failureHistory: z.array(z.object({ date: z.string(), type: z.string() })).optional() }), outputSchema: z.object({ maintenanceNeeded: z.boolean(), urgency: z.enum(['low', 'medium', 'high', 'critical']), estimatedDays: z.number(), recommendation: z.string() }), handler: async (input: unknown) => { const d = input as Record<string, unknown>; const cycles = Number(d['cycleCount']); const urgency = cycles > 50000 ? 'critical' as const : cycles > 30000 ? 'high' as const : cycles > 15000 ? 'medium' as const : 'low' as const; return { maintenanceNeeded: urgency !== 'low', urgency, estimatedDays: urgency === 'critical' ? 1 : urgency === 'high' ? 7 : 30, recommendation: cycles > 30000 ? 'Agendar manutenção preventiva imediatamente' : 'Monitorar e agendar em 30 dias' } } }]) }
export function createFabricationTracker() { return makeAgent('ag-006', 'fabrication-tracker', 'observer', 'mold-making', 'Acompanha progresso de fabricação do molde, alerta sobre atrasos no cronograma.', [{ name: 'mold.trackFabrication', description: 'Track fabrication progress', inputSchema: z.object({ moldId: z.string(), currentPhase: z.string(), estimatedCompletion: z.string(), phases: z.array(z.object({ name: z.string(), status: z.enum(['pending', 'in_progress', 'completed', 'delayed']), progress: z.number(), dueDate: z.string() })) }), outputSchema: z.object({ overallProgress: z.number(), delayedPhases: z.array(z.string()), estimatedDelay: z.number(), alerts: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as { phases: Array<{ name: string; status: string; progress: number }> }; const progress = d.phases.reduce((s, p) => s + p.progress, 0) / d.phases.length; const delayed = d.phases.filter(p => p.status === 'delayed'); return { overallProgress: Math.round(progress), delayedPhases: delayed.map(p => p.name), estimatedDelay: delayed.length * 5, alerts: delayed.length > 0 ? [`${delayed.length} fases atrasadas — impacto estimado: ${delayed.length * 5} dias`] : [] } } }]) }
export function createCNCScheduler() { return makeAgent('ag-007', 'cnc-scheduler', 'decision-maker', 'cnc-machining', 'Otimiza scheduling de máquinas CNC: prioridade, setup time, disponibilidade de ferramentas.', [{ name: 'cnc.schedule', description: 'Optimize CNC schedule', inputSchema: z.object({ jobs: z.array(z.object({ jobId: z.string(), estimatedHours: z.number(), priority: z.enum(['low', 'normal', 'high', 'urgent']), requiredTools: z.array(z.string()), deadline: z.string() })), machines: z.array(z.object({ machineId: z.string(), availableHours: z.number(), toolSet: z.array(z.string()) })) }), outputSchema: z.object({ schedule: z.array(z.object({ jobId: z.string(), machineId: z.string(), startSlot: z.number(), estimatedCompletion: z.string() })), unscheduled: z.array(z.string()), utilization: z.number() }), handler: async (input: unknown) => { const d = input as { jobs: Array<{ jobId: string; estimatedHours: number }>; machines: Array<{ machineId: string; availableHours: number }> }; const schedule = d.jobs.slice(0, d.machines.length).map((j, i) => ({ jobId: j.jobId, machineId: d.machines[i]!.machineId, startSlot: i * 2, estimatedCompletion: new Date(Date.now() + j.estimatedHours * 3600000).toISOString() })); const unscheduled = d.jobs.slice(d.machines.length).map(j => j.jobId); return { schedule, unscheduled, utilization: 78 } } }]) }
export function createToolWearMonitor() { return makeAgent('ag-008', 'tool-wear-monitor', 'observer', 'cnc-machining', 'Monitora desgaste de ferramentas, prediz momento de troca baseado em horas de uso e material.', [{ name: 'cnc.monitorToolWear', description: 'Monitor tool wear', inputSchema: z.object({ toolId: z.string(), hoursUsed: z.number(), maxLifeHours: z.number(), materialMachined: z.string(), lastReplaced: z.string() }), outputSchema: z.object({ wearPercent: z.number(), hoursRemaining: z.number(), needsReplacement: z.boolean(), recommendation: z.string() }), handler: async (input: unknown) => { const d = input as Record<string, unknown>; const used = Number(d['hoursUsed']); const max = Number(d['maxLifeHours']); const pct = Math.round((used / max) * 100); return { wearPercent: pct, hoursRemaining: Math.max(0, max - used), needsReplacement: pct > 80, recommendation: pct > 90 ? 'Trocar imediatamente' : pct > 80 ? 'Agendar troca esta semana' : 'Dentro do normal' } } }]) }
export function createNCProgramValidator() { return makeAgent('ag-009', 'nc-program-validator', 'decision-maker', 'cnc-machining', 'Valida programas NC antes da execução: colisões, limites de eixo, velocidades seguras.', [{ name: 'cnc.validateProgram', description: 'Validate NC program', inputSchema: z.object({ programId: z.string(), machineId: z.string(), axisLimits: z.object({ x: z.number(), y: z.number(), z: z.number() }), toolpaths: z.array(z.object({ toolId: z.string(), maxX: z.number(), maxY: z.number(), maxZ: z.number(), feedRate: z.number(), spindleSpeed: z.number() })) }), outputSchema: z.object({ valid: z.boolean(), collisions: z.array(z.string()), speedWarnings: z.array(z.string()), axisViolations: z.array(z.string()) }), handler: async (input: unknown) => { const d = input as { axisLimits: { x: number; y: number; z: number }; toolpaths: Array<{ maxX: number; maxY: number; maxZ: number; feedRate: number; spindleSpeed: number }> }; const violations = d.toolpaths.filter(t => t.maxX > d.axisLimits.x || t.maxY > d.axisLimits.y || t.maxZ > d.axisLimits.z); const speedWarnings = d.toolpaths.filter(t => t.feedRate > 5000 || t.spindleSpeed > 12000); return { valid: violations.length === 0 && speedWarnings.length === 0, collisions: [], speedWarnings: speedWarnings.map(t => `Ferramenta com feedRate ${t.feedRate} acima do limite`), axisViolations: violations.map(() => 'Violação de limite de eixo') } } }]) }
