import { z } from 'zod'

export const MoldDesignedPayload = z.object({ moldId: z.string().uuid(), productId: z.string().uuid(), moldCode: z.string().optional(), cavityCount: z.number().int().positive(), steelType: z.string().min(1), coolingConfig: z.string().optional(), ejectorType: z.string().optional(), estimatedCycleLife: z.number().int().optional(), estimatedCycleTimeSec: z.number().optional(), cadFileHash: z.string().optional(), designedAt: z.string().datetime(), designedBy: z.string().optional() })
export const MoldFabricationCompletedPayload = z.object({ moldId: z.string().uuid(), fabricationDurationDays: z.number().optional(), actualSteelType: z.string().optional(), actualCavityCount: z.number().int().optional(), fabricatorName: z.string().optional(), qualityCheckResult: z.enum(['passed','failed','rework_required']).optional(), completedAt: z.string().datetime() })
export const MoldDeliveredPayload = z.object({ moldId: z.string().uuid(), deliveredTo: z.string().min(1), deliveryLocation: z.string().optional(), deliveredAt: z.string().datetime(), receivedBy: z.string().optional() })
export const MoldInstalledPayload = z.object({ moldId: z.string().uuid(), machineId: z.string().min(1), machineName: z.string().optional(), installedAt: z.string().datetime(), installedBy: z.string().optional(), setupSheetId: z.string().optional() })
export const MaintenanceScheduledPayload = z.object({ maintenanceId: z.string().uuid(), moldId: z.string().uuid(), type: z.enum(['preventive','corrective','inspection']), scheduledDate: z.string(), reason: z.string().optional(), currentCycleCount: z.number().int().optional(), cycleCountAtSchedule: z.number().int().optional(), assignedTechnician: z.string().optional() })
export const MaintenancePerformedPayload = z.object({ maintenanceId: z.string().uuid(), moldId: z.string().uuid(), type: z.string().optional(), findings: z.string().optional(), actionsTaken: z.string().optional(), partsReplaced: z.array(z.string()).optional(), downtimeHours: z.number().optional(), cost: z.number().optional(), performedAt: z.string().datetime(), performedBy: z.string().optional(), nextMaintenanceCycles: z.number().int().optional() })
export const CycleLimitReachedPayload = z.object({ moldId: z.string().uuid(), currentCycles: z.number().int(), maxCycles: z.number().int(), overPercent: z.number().optional(), materialProcessedKg: z.number().optional(), detectedAt: z.string().datetime(), actionRequired: z.string().optional() })
export const MoldFailureDetectedPayload = z.object({ moldId: z.string().uuid(), machineId: z.string().optional(), failureType: z.enum(['crack','wear','deformation','cooling_leak','ejection_failure']), severity: z.enum(['minor','major','critical']), cyclesAtFailure: z.number().int().optional(), detectedAt: z.string().datetime(), immediateAction: z.string().optional() })
export const MoldInspectionCompletedPayload = z.object({ inspectionId: z.string().uuid(), moldId: z.string().uuid(), result: z.enum(['approved','rejected','requires_maintenance']), findings: z.array(z.string()).optional(), dimensionalCheck: z.boolean().optional(), surfaceFinishCheck: z.boolean().optional(), coolingChannelCheck: z.boolean().optional(), inspectedAt: z.string().datetime(), inspectedBy: z.string().optional() })
